validator:
  basic: yes
save_pipeline: yes
channels:
- number: 13
  sample_rate: 2000
  type: LFP
- number: 14
  sample_rate: 2000
  type: LFP
- number: 15
  sample_rate: 2000
  type: LFP
- number: 16
  sample_rate: 2000
  type: LFP
- number: 17
  sample_rate: 2000
  type: LFP
- number: 18
  sample_rate: 2000
  type: LFP
- number: 19
  sample_rate: 2000
  type: LFP
- number: 20
  sample_rate: 2000
  type: LFP
- number: 21
  sample_rate: 2000
  type: LFP
- number: 22
  sample_rate: 2000
  type: LFP
- number: 23
  sample_rate: 2000
  type: LFP
- number: 24
  sample_rate: 2000
  type: LFP
- number: 25
  sample_rate: 2000
  type: LFP
- number: 26
  sample_rate: 2000
  type: LFP
- number: 27
  sample_rate: 2000
  type: LFP
- number: 28
  sample_rate: 2000
  type: LFP
- number: 29
  sample_rate: 2000
  type: LFP
- number: 30
  sample_rate: 2000
  type: LFP
subject_code: YAB
project_name: test2
file_format: 1.0
blocks:
- 008
- '010'
- '011'
- '012'
physical_unit: as-is
