project_name: "test1"
subject_code: "YAB"
save_pipeline: yes
electrodes: "1-84"
signal_source: "notch/{block}"
save_plots:
  wavelet_kernel:
    width: 12
    height: 7
    useDingbats: no
    font_size_level: 1
  diagnosis:
    width: 7
    height: 12
    useDingbats: no
    font_size_level: 1
    duration: 10
wavelet:
  downsample_rate: 100
  demean: yes
  frequencies: "{seq(2, 200, by = 20)}"
  kernel_cycle:
    - 3
    - 20
