#!/usr/bin/env bash

set -e

# Prepare log file
log_file="{{ log_file }}"
if [[ ! -z "$log_file" ]]; then
  log_path="{{ log_path }}"
  log_file="{{ log_path }}/$log_file"
  mkdir -p "$log_path" && touch "$log_file" && echo "Started: $(date -u)" >> "$log_file"
  echo --------------------------------------------------------
  echo Log file: "$log_file"
  echo --------------------------------------------------------
else
  log_file="/dev/null"
fi

# Prepare working directory: FreeSurfer does not like it when
# directories contain spaces
wdir_actual="{{ work_path_actual }}"
wdir_fs="{{ work_path_symlink }}"
mri_path="{{ mri_path }}"
input_name="{{ gsub('.*\\.(nii|nii\\.gz)$', 'MRI.\\1', mri_path) }}"
mri_ext="{{ ifelse(grepl('gz$', mri_path, ignore.case = TRUE), '.nii.gz', '.nii') }}"
meta_path="$wdir_actual/rave-imaging/meta"

# Make sure the actual working directory exists
fresh_start={{ ifelse(overwrite, 1, 0) }}
if [[ "$fresh_start" -eq 1 && -d "$wdir_actual/rave-imaging/fs" ]]; then
  rm -r "$wdir_actual/rave-imaging/fs"
fi
mkdir -p "$wdir_actual/rave-imaging/meta"

# Back up original MRI file to meta folder
cp -f "$mri_path" "$wdir_actual/rave-imaging/meta/MRI_RAW$mri_ext"

touch "$meta_path/conf-reconstruction.txt"
echo "% Do NOT edit this file!" > "$meta_path/conf-reconstruction.txt"
echo "profile: FreeSurfer Re-construction"
echo "input_image: inputs/MRI/{{ basename(mri_path) }}" >> "$meta_path/conf-reconstruction.txt"
echo "input_backup: meta/MRI_RAW$mri_ext" >> "$meta_path/conf-reconstruction.txt"
echo "fs_normalized_image: fs/mri/T1.mgz" >> "$meta_path/conf-reconstruction.txt"
echo "fs_normalized_backup: meta/T1.nii" >> "$meta_path/conf-reconstruction.txt"
echo "fs_Norig: meta/transform-Norig.mat" >> "$meta_path/conf-reconstruction.txt"
echo "fs_Torig: meta/transform-Torig.mat" >> "$meta_path/conf-reconstruction.txt"

# Make sure the symlink is done properly
if [[ -d "$wdir_fs" ]]; then
  rm -r "$wdir_fs"
fi
mkdir -p "$wdir_fs"
ln -s "$wdir_actual/rave-imaging" "$wdir_fs"

# Set FreeSurfer home directory & initialize
SUBJECTS_DIR="$wdir_fs/rave-imaging"
{{
  if(length(freesurfer_home) == 1 && !is.na(freesurfer_home) && file.exists(freesurfer_home)) {
    sprintf(
      'FREESURFER_HOME="%s"\nsource "$FREESURFER_HOME/SetUpFreeSurfer.sh"',
      freesurfer_home
    )
  } else { "" }
}}

if [ -d "$SUBJECTS_DIR/fs/mri" ]; then
  # Use existing FreeSurfer directory to continue analysis
  recon-all -sd "$SUBJECTS_DIR" -sid fs {{ paste(c(args, ""), collapse = " ") }}| tee -a "$log_file"
else
  # Copy Nifti input
  cp "$mri_path" "$wdir_fs/$input_name"
  if [ -d "$SUBJECTS_DIR/fs" ]; then
    rm -r "$SUBJECTS_DIR/fs"
  fi
  recon-all -sd "$SUBJECTS_DIR" -sid fs -i "$wdir_fs/$input_name" {{ paste(c(args, ""), collapse = " ") }}| tee -a "$log_file"
fi

# Convert T1.mgz to T1.nii so users can choose to use T1.nii to coregister
mri_convert --in_type mgz --out_type nii "$SUBJECTS_DIR/fs/mri/T1.mgz" "$SUBJECTS_DIR/fs/mri/T1.nii"

cp -f "$SUBJECTS_DIR/fs/mri/T1.nii" "$meta_path/T1.nii"

# Generate transform matrices
mri_info --vox2ras "$meta_path/T1.nii" > "$meta_path/transform-Norig.mat"
mri_info --vox2ras-tkr "$meta_path/T1.nii" > "$meta_path/transform-Torig.mat"

echo "Done." | tee -a "$log_file"

## END OF RAVE Script: FreeSurfer recon-all with flags: {{ paste(c(args, ""), collapse = " ") }} ##
