project_name: "PROJECT_NAME"
subject_code: "SUBJECT_CODE"
save_pipeline: yes
epoch: auditory_onset
electrodes: 14-16
reference: default
intervals:
- - -1.0
  - 2.0
type:
  - "power"
baseline:
- - -1
  - -0.2
baseline_method: "decibel"
