# Do not remove these two lines of python code

# rave_pipeline_adapters is a sub-module that tells RAVE how to 
# serialize/unserialize python objects generated by the pipeline
from . import rave_pipeline_adapters

# Functions in ./shared will be automatically loaded and available to main.Rmd
# during the evaluations. 
from .shared import *

